### ISSUE TITLE
My Bee2.4 dosen't work.

### ISSUE THREAD

**Issue by FriskRD** [FriskRD/bee2-error#1]
I have the latest version of BEE2.But the issue is that when i rebuild the testchamber,it dosen't work.It's completing the Geometry Bar,but the rest of them no!Can anyone help me?

**Comment by TheDarkBomber** [comment]
Why did you create a repository to post this issue? Post it on the BEE2.4 repository.

**Comment by FriskRD** [comment]
how?!

**Comment by LautaroL20** [comment]
LOL, just go here then click "New Issue" green button at the right top of the page: https://github.com/BEEmod/BEE2-items/issues
